config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

mount Sidekiq::Web, at: "/sidekiq"
get 'top/index'

devise_for :admin_user, controllers: {
  sessions:      'admin_user/sessions',
  passwords:     'admin_user/passwords',
  registrations: 'admin_user/registrations'
}
devise_for :members, controllers: {
  sessions:      'members/sessions',
  passwords:     'members/passwords',
  registrations: 'members/registrations'
}

  resources :top
  get 'rsslist/index'
  get 'rsslist/new'
  post 'rsslist/create', as: :rsslists

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    root 'rsslist#index'

end

app/models/rsslist.rb
# == Schema Information
#
# Table name: rsslists
#
#  id         :integer          not null, primary key
#  url        :string
#  member_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_rsslists_on_member_id                 (member_id)
#  index_rsslists_on_member_id_and_created_at  (member_id,created_at)
#

class Rsslist < ActiveRecord::Base
  belongs_to :member
  has_many :sites

  default_scope -> { order(created_at: :desc) }
  validates :url, presence: true
  validates :member_id, presence: true
end

app/controllers/rsslist_controller.rb
class RsslistController < ApplicationController
  before_action :sign_in_required
  def index
    @favorites = Array.new
    urls = Rsslist.where(member_id: current_member.try(:id)).pluck(:url)
    urls.each do |url|
      next unless feed = Feedbag.find(url).last
      site = Feedjira::Feed.fetch_and_parse(feed)
      site_data = Hash.new
      entries = Hash.new
      site.entries.each_with_index do |entry,i|
        /<img(.)src=\"?([-_.!~\\'()a-z0-9\;\/\?:@&=+\$\,\%#]+(jpg|jpeg|gif|png|bmp))/i =~ entry.content
        entry_image = $2
        entries[i] = {:entry_title   => entry.title,
                      :entry_url     => entry.url,
                      :entry_summary => entry.summary,
                      :entry_image   => entry_image}
        break if i == 4
      end

      site_data = {:site_title => site.title,
                   :site_url   => site.url,
                   :entries    => entries }
      @favorites << site_data
    end
    return @favorites
  end


  def new
    @rsslist = Rsslist.new
  end

  def create
    @rsslist = current_member.rsslists.build(rsslist_params)
    if @rsslist.save
      redirect_to(root_url)
    else
      render 'new'
    end
  end

  private
  def rsslist_params
    params.require(:rsslist).permit(:url)
  end
end

app/helpers/rsslist_helper.rb
module RsslistHelper
end

app/views/rsslist/index.html.erb
<div class="mdl-grid">
<% @favorites.each do |favorite| %>
  <% 4.times do |i| %>
  <div class="mdl-cell mdl-cell--6-col">
    <div class="mdl-card  mdl-shadow--2dp">
      <div class="thumbnail">
        <a href=' <%= favorite[:entries][i][:entry_url] %> ' target="blank">

        <% if favorite[:entries][i][:entry_image] %>
        <img src="<%= favorite[:entries][i][:entry_image] %>" height="182px" width="182px" alt="Noimage" title="Noimage">
        <% else %>
        <img src="<%= asset_path "noimage.jpg" %>" height="182px" width="182px" alt="Noimage" title="Noimage">
        <% end %>

        </a>
      </div>
        <div class="mdl-card__supporting-text">
          <h2><a href=' <%= favorite[:entries][i][:entry_url] %> ' target="blank"><%= favorite[:entries][i][:entry_title] %></a></h2>
          <div class="description">
          <%= "ここにディスクリプションを表示"*10 %>
          </div>
          <div class="links">引用元 : <a href=' <%= favorite[:site_url] %>' target="blank" ><%= favorite[:site_title] %></a>
          </div>
        </div>
    </div>
  </div>
  <% end %>
<% end %>

<div class="mdl-cell mdl-cell--6-col">
 <a href="http://localhost:3000/rsslist/new">
  <div class="new-rss-bottom">
      <button class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
        <i class="material-icons">add</i>
        <div class="button-tag">New</div>
      </button>
  </div>
 </a>
</div>

<%= link_to "新規登録",rsslist_new_path %>

</div>




app/views/rsslist/new.html.erb
<%= form_for(@rsslist) do |f| %>

  <div class="field">
    <%= f.label :url, "サイトURL" %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit "登録する" %>
  </div>
<% end %>