config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

mount Sidekiq::Web, at: "/sidekiq"
get 'top/index'

devise_for :admin_user, controllers: {
  sessions:      'admin_user/sessions',
  passwords:     'admin_user/passwords',
  registrations: 'admin_user/registrations'
}
devise_for :members, controllers: {
  sessions:      'members/sessions',
  passwords:     'members/passwords',
  registrations: 'members/registrations'
}

  resources :top
  get 'rsslist/index'
  get 'rsslist/new'
  post 'rsslist/create', as: :rsslists

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    root 'rsslist#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RSS-Readerを作る</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>





<!-- Always shows a header, even in smaller screens. -->
<header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">RSS-Readerを作る</span>
      <% if member_signed_in? || admin_user_signed_in? %>
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <%= link_to 'ログアウト', destroy_member_session_path || destroy_admin_user_session_path, {:class => "mdl-navigation__link", :method => "delete" } %>
        <%= link_to 'User', root_path, {:class => "mdl-navigation__link"} %>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
      </nav>
      <% end %>
    </div>
</header>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">

<% if member_signed_in? || admin_user_signed_in? %>
  <div class="mdl-layout__drawer">

    <div class="login-info-side">
      <p>こんにちは</p>
      <p><strong><%= current_member.try(:email) || current_admin_user.try(:email) || "" %></strong>さん。</p>
    </div>

    <span class="mdl-layout-title">My Project</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="">RSSリーダー</a>
      <a class="mdl-navigation__link" href="">Speed Dial</a>
      <a class="mdl-navigation__link" href="">Link</a>
      <a class="mdl-navigation__link" href="">ログアウト</a>
    </nav>
  </div>
<% end %>

  <main class="mdl-layout__content" <% unless member_signed_in? || admin_user_signed_in? %> style="margin: 0 auto;"<% end %> >
        <%= yield %>
  </main>
</div>



</body>
</html>